# The URL the site will be built for
base_url = "https://cnwzhjs.github.io"

title = "Have a bite"
description = "Tony Huang's personal blogs"

default_language = "en"
theme = "even"

generate_feed = true
feed_filename = "atom.xml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    {name = "categories", feed = true},
    {name = "tags", feed = true},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

external_links_target_blank = true

[extra]
# Put all your custom variables here
author = "Tony Huang"
even_title = "Have a bite"